---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alerta-helm.fullname" . }}-read-config
  namespace: {{ include "alerta-helm.namespace" . }}
data:
  alertad.conf: |-
    CORS_ORIGINS = [r'https?://*philips-healthsuitechina.com.cn*']