---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alerta-helm.fullname" . }}-read
  namespace: {{ include "alerta-helm.namespace" . }}
  labels:
    app: {{ include "alerta-helm.fullname" . }}-read
    {{- include "alerta-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.read.autoscaling.enabled }}
  replicas: {{ .Values.read.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "alerta-helm.fullname" . }}-read
      {{- include "alerta-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "alerta-helm.fullname" . }}-read
        {{- include "alerta-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alerta-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "alerta-helm.fullname" . }}-read-volume
          configMap:
            name: {{ include "alerta-helm.fullname" . }}-read-config
      containers:
        - name: {{ include "alerta-helm.fullname" . }}-read
          {{- with .Values.read.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.read.image.repository }}:{{ .Values.read.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: {{ include "alerta-helm.fullname" . }}-read
              containerPort: {{ .Values.read.service.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ include "alerta-helm.fullname" . }}-read-volume
              mountPath: {{ .Values.read.volumeMountPath }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}